### PR TITLE
docs: Correct a broken link

### LINKED ISSUE #69: Contribution Guidelines link does not redirect to documentation
**Description of issue**

Clicking the Contribution Guidelines link is not redirected to a session.

**Usage example**

Go to the github.com/rocketseat/unform link -> access the documentation in the Index section -> click the Contribution Guidelines link.

### PR DESCRIPTION
**Pull request by Ruttmann**
Correct the summary link to Contribution Guidelines subsection.

Close #69. [skip ci]

**Changes proposed**
Just corrected the line 68 of the README.md file, according to my comment on issue #69 

From:
`- [Contribution Guidelines](#contributing-guide)`

To:
`- [Contribution Guidelines](#contribution-guidelines)`

### CODE REVIEW

**Comment by Ruttmann** [comment]
I did a second commit, because my editor Prettier config had changed some double quotes at the code blocks. Now everything is correct again.

**Comment by Ruttmann** [comment]
I'm facing some problems with VSCode, most specifc, Prettier is somehow taking out all the semicolons that I add at the end of a function. I have deleted all Prettier configs in settings.json, but the problem still. Do you know how can I correct that? I have ESLint and Prettier correctly installed to VSCode and the only configuration regarding Prettier in my settings.json are the following:
```
"prettier.eslintIntegration": true,
"prettier.semi": true
```

Anyone knows what can I do to avoid that?

**Comment by diego3g** [comment]
@Ruttmann Try removing Prettier extension and add these settings to VSCode:
```json
"eslint.autoFixOnSave": true,
"editor.formatOnSave": false,
"eslint.validate": [
  {
    "language": "javascript",
    "autoFix": true
  },
  {
    "language": "javascriptreact",
    "autoFix": true
  },
  {
    "language": "typescript",
    "autoFix": true
  },
  {
    "language": "typescriptreact",
    "autoFix": true
  }
]
```

**Comment by Ruttmann** [comment]
I've made a new commit. Can you please verify if everything is ok now?

**Comment by pellizzetti** [comment]
Fixing conflicts on this branch, I ended up realizing that a PR (#35) that was merged earlier today [solved this](https://github.com/Rocketseat/unform/pull/35/files#diff-04c6e90faac2675aa89e2176d2eec7d8R44).

Sorry about that, we are grateful for your contribution. ❤️

**Pull request closed without merging**
