### PR TITLE
docs: Add react-tag-input example

### PR DESCRIPTION
**Pull request by thiagodesouza**
Add `react-tag-input` example into README.md.

### CODE REVIEW

**Comment by diego3g** [comment]
Hello @thiagodesouza, great example and contribution! 🎉 

Can you please provide us a Code Sandbox with a example of it working with unform? It would be great so we can see it in action before merging.

Also, we have an `example` folder inside the project where you can add this example so others can see it in action in new contributions.

**Comment by thiagodesouza** [comment]
Hi, Diego!

Thanks for your feedback.

The example has been included (:

**Comment by thiagodesouza** [comment]
Hi, @jpdemagalhaes! 

The `react-select` component have default options (closed) and the `react-tag-input` don't have pre-defined options. 

Example: https://github.com/thiagodesouza/vuttr-app

**Comment by thiagodesouza** [comment]
Hi, @jpdemagalhaes !

Yes, you are right! I'm sorry. 

(:

**Pull request closed without merging**
