### PR TITLE
feat: Add react-native suport

### PR DESCRIPTION
**Pull request by italomlp**
Add react-native support for TextInput components

**Changes proposed**
So, I was reading #42 and think that I could make an initial code for it. Here I am. 

To make Unform work in React Native, I added it in `devDependencies`, and made an example folder to RN too, linking dependencies that are already in use on the main `package.json`. The example is working, you can check it out.

To use the native part, we can import with `import {} from '@rocketseat/unform/native'`.

I had to think a little on how to work with the submit of the form. Ended in a hook: `useSubmit`. Like `useField`, we need to wrap it in a component, like a `SubmitButton` (maybe we can provide a standard one too). So, it will return a function (`handleSubmit`) that we can call by passing to the Touchable `onPress`. This function will call the original `handleSubmit`, that catches the `onSubmit` passed to the `Form` component, like in the ReactJS version.

The `Form` component turns a RN `View` without HTML-like props. The same to `Input`, but with RN `TextInput`. In `Input`, the value is provided by the prop `_lastNativeProps` from the input ref. Sadly, we can't (at least I can't find a way) change this prop. So, when the initialValues are defined, and if the user didn't change the fields, the `_lastNativeProps` is `undefined`. Then we fall back to the `defaultValue`.

The validation seems to work fine. Also the Scope and the `resetForm`.

I was creating this Draft PR to get some opinions about my approach. If all fine, I'll write tests and improve what is needed as soon as possible. Suggestions and reviews are welcome. I think that still have some redundant code (see the both `lib/Form.tsx` and `lib/native/Form.tsx`), and still thinking about how to achieve this.

**Additional context**
By making this, I got me trying to get the form data out of the handle submit function. I found what I think is a good way to make this (like the useSubmit hook). Will open an issue soon to discuss if it is welcome. 😃

### CODE REVIEW

**Comment by diego3g** [comment]
Great @italomlp! I think that we should not duplicate our codebase as the elements itself, we should maybe adapt them to work when React Native is present. I will take a look at the code base and suggest something this week.

**Comment by italomlp** [comment]
@diego3g I was thinking. In the way that I did it, the only things duplicated are the Form.tsx and the Input.tsx (all the other things are exported without duplicating them in native too, but only for the user don't need to import them from the default way). I believe that these components should be different in native, but as they have much code in common with the DOM version (the code of the main functionality), we can make a CoreForm.tsx, and reuse it properly in both DOM and native. What do you think about this approach? If good, I can do these changes tonight. 
Another option is that we can check if Unform is running with react-native, and choose the proper component/element to use in Form.tsx and Input.tsx. But I confess that I don't like it this way. Seems like a quick fix/kludge to me. Only my two cents 😄 .

**Comment by diego3g** [comment]
@italomlp Maybe Form element must be splited from Form component itself, i mean, we should not duplicate Form file between web and native version, maybe we should have an Form component apart from the functional part of form as parseData and all of the other stuff, what do you think? With that i think we'll be really close to a release candidate implementation.

**Comment by italomlp** [comment]
@diego3g It's good too. I'll make it as soon as possible, and include tests too. About the submit approach and import way, all good?

**Comment by diego3g** [comment]
@italomlp I think we should not have `useSubmit` hook, instead we should have an `useForm` hook that exposes more than the submit API, what you think about it? We are discussing it here #76.

We could have something like this:
```js
import React from 'react';
import { useForm } from 'react';

export default function () {
  const [Form, { submitForm, resetForm, setFieldValue, getFieldValue }] = useForm();

  return (
    <Form />
  );
}
```

Another option would be not retuning `Form` from `useForm` and just retuning one way to connect the forms. Something like this:
```js
import React from 'react';
import { Form, useForm } from 'react';

export default function () {
  const { submitForm, resetForm, setFieldValue, getFieldValue } = useForm('#myform');

  return (
    <Form id="myform">
      
    </Form>
  );
}
```

What do you think about this API?

@jpdemagalhaes can you give you thoughts on it?

**Comment by italomlp** [comment]
@diego3g Yes, I confess that I thought about it from the begin haha. What I thought:

We can work only with hooks, transforming the main Form into one (maybe passing initialValues and other props like schema, etc. in the useForm hook), and use more or less like you described in the first approach. So, we export the Scope element, the Input element too (the core ones), like is already done, and use them normally:

```jsx
import React from 'react';
import { useForm, Scope, Input } from '@rocketseat/unform';

const initialValues = {
  fullName: 'Italo Menezes',
  address: {
    country: 'Brazil'
  }
}

const schema = { // ... }

export default function () {
  const [Form, { submitForm, resetForm, setFieldValue, getFieldValue }] = useForm({ initialValues, schema });

  return (
    <Form>
      <Input name="fullName" />
      <Scope path="address">
        <Input name="country" />
      </Scope>
    </Form>
  );
}
```
The second way you suggested seems less powerful and less beautiful to me haha. Waiting for more opinions here.

If we use it in this way, could we make it in this PR (as I started this work with the submit) or open another one?

**Comment by diego3g** [comment]
@italoiz I think the first approach is prettier too, but it will probably cause some problems with the current version so it will be a big change in unform. I would really appreciate a little bit more discussion here. 

@jpdemagalhaes @pellizzetti can you share your thoughts about this?

**Comment by italomlp** [comment]
@diego3g @jpdemagalhaes @pellizzetti I was thinking. I making an app with RN, and want to use Unform on it. I will do a bit of change accordingly to what we talk here, and use my fork while we decide things. Soon, you can see these changes on my repo (I will let a message here), review if it's ok and what has to be better to release that on official repo. Thanks

**Comment by diego3g** [comment]
@italomlp I'm spending some time thinking about a full-hooks API so we can have all the functionalities we're discussing in this pull request.

**Comment by italomlp** [comment]
I'm closing this draft PR, as Unform v2.0 will bring RN support out of the box. Thanks to the Rocketseat team!

**Pull request closed without merging**
