### PR TITLE
docs: Add description to select element section

### PR DESCRIPTION
**Pull request by MorenoMdz**
**Changes proposed**
A simple description that explains the structure needed to add the options list to the select element.

### CODE REVIEW

**Comment by diego3g** [comment]
@MorenoMdz I didn't understand what this documentation is about, are you talking about `defaultValue` of select element? If yes, then you must explicitly say that in the documentation.

**Comment by MorenoMdz** [comment]
The idea is to clarify the structure each option item should have.

**Comment by diego3g** [comment]
Maybe we can clarify it even better, i mean by something like this:

Every `<Select />` component must receive `options` property with an array of option. Every option inside this array must be an object with `id` and `title` as shown in the example below.

What do you think about it @MorenoMdz?

Please, if you'll edit the content of your commit, just amend with the last commit instead of creating a new one, also please follow our commiting rules so keep the first letter of the commit subject in uppercase: `docs: Add description to select element section`.

Also please keep your commit body within 72 characters length, so it will be something like this:

```
Simple description that explains the structure needed to add the option
list to the select element.
```

**Comment by MorenoMdz** [comment]
Alright, I will update it later tonight, I misread the subject part as it said the *type* should be lowercase and I missed that the subject should be capitalized.

**Pull request merged**
