### PR TITLE
docs(readme): add good first issue

### PR DESCRIPTION
**Pull request by nidelson**
Add section `Good First Issue` in `Readme` to encourage early contributions.

### CODE REVIEW

**Comment by santospatrick** [comment]
Your pull request is not valid because your commits dont follow this project conventions, a valid message would be: 

`docs(readme): add good first issue`

Check [this link](https://github.com/conventional-changelog/commitlint#what-is-commitlint) to get more info about commitlint

**Comment by nidelson** [comment]
Tks @santospatrick

**Comment by nidelson** [comment]
@diego3g Como solicitar ao CI para validar novamente? Já foi corrigido a título.
Esta PR está parada à muito tempo.

**Comment by diego3g** [comment]
Hello @nidelson, thanks for the contribution!

As we were working on Unform 2.0, we were not considering the existing PR's as a lot of changed would be included in this version.

Now that Unform 2.0 is released we're reviewing the PR's.

Can you send a new PR as we changed all of the README?

Then you can send the PR only with one commit with the right name :)

Thanks 💜

**Pull request closed without merging**
