### PR TITLE
docs: Add a docusaurus project

### PR DESCRIPTION
**Pull request by leonardobrito**
**Changes proposed**

Docusaurus makes documentation easy and works with many languages.

Now one folder named docs has a docusaurus project.

**Additional context**

From docusaurus it is possible to create the documentation website with support to many languages and publish on github pages.

Captura de Tela 2019-05-26 às 18 28 14

Some changes have to be make before publish like: change the favicon, the color i don't know if is correct, in the footer the image did not looks good and others things. I has use the style and others from [https://github.com/Rocketseat/docs](https://github.com/Rocketseat/docs) as reference.

### CODE REVIEW

**Comment by diego3g** [comment]
@leonardobrito I think you're talking to @aldroydzito so just to keep in mind, we need an easy way to add translation to our documentation and if Docosaurus is not the best option here, we might need another option. Maybe using some kind of static site generator and not a documentation framework itself.

**Comment by leonardobrito** [comment]
@diego3g i agree. I've worked with Ruby on rails to solve problems of i18n, but i think Rails is to much to solve our problem. I'll look for something more simple to solve this, and i'll talk to @aldroydzito about.

**Comment by aldroydzito** [comment]
@diego3g We actually talked about it and there's a way to translate manually. I think we should keep with Docusaurus.

**Comment by mmCodingjs** [comment]
Personally speaking, I don't like the idea of installing a package to just translate itself.

**Pull request merged**
