### PR TITLE
initial data description

### PR DESCRIPTION
**Pull request by MorenoMdz**
**Changes proposed**
Small description of the Initial Data section.

### CODE REVIEW

**Comment by diego3g** [comment]
@MorenoMdz It seems that your Prettier changed a lot of stuff inside README, can you take a look at it and rollback to the older version just adding you comment to Initial Data docs?

**Comment by MorenoMdz** [comment]
Alright.

**Comment by MorenoMdz** [comment]
From the previous version, I have added the Initial Data info and a proper commit message. Let me know if there is anything else to improve.

**Comment by diego3g** [comment]
@MorenoMdz Your commit with wrong message is still in this PR, please delete the old commit and keep it only in one commit named: `docs: Add description to the Initial Data section`.

Talk to me on Discord if you need any help.

**Pull request closed without merging**
