### PR TITLE
feat: Add aria attr for invalid fields

### PR DESCRIPTION
**Pull request by eduardoborges**
**Changes proposed**

In order to improve the accessibility and styling of fields that have errors, based on the specification, I suggest adding an attribute that indicates it.

Just this ;D

### CODE REVIEW

**Comment by emilioheinz** [comment]
Really good improvement, but i think you should improve the tests for theses fields too.

**Comment by eduardoborges** [comment]
I thing the error is not in the test, they are ok.
You can re-run the Travis build?

**Comment by emilioheinz** [comment]
I mean... Did you write any tests for these changes?

**Comment by diego3g** [comment]
Hello @eduardoborges, thanks for the contribution!

As we were working on Unform 2.0, we were not considering the existing PR's as a lot of changed would be included in this version.

Now that Unform 2.0 is released we're reviewing the PR's.

In this new version, Unform does not exposes any input element from within the package, so the user must create all the input sources, so we do not have Input, Select, Choice, etc anymore.

So i think your PR can't be merged anymore.

Instead you can add your tip to Unform Simple Input docs: https://unform.dev/recipes/simple-input

Thanks for the contribution again and feel free to open more PR's 💜

**Pull request closed without merging**
