### PR TITLE
feat: Add file input support

### PR DESCRIPTION
**Pull request by italoiz**
**Changes proposed**

Send files easily by adding new fields of type `FileInput`.

**Additional context**

With the `FileInput` component you can also retrieve the progress of the upload when it is loaded into memory. This can be useful for blocking some buttons while the process is not complete preventing incomplete file data from being sent.

Example:

```jsx
<FileInput name="attach" onStartProgress={(progress) => console.log(progress)} />
```

### CODE REVIEW

**Comment by diego3g** [comment]
Hi @italoiz, first of all, thanks for your contribution!

1. Can you please merge your PR with our last commits on master soon as we made some changes on prettier. You can see that your `lib/index.ts` file has now double quotes instead single quotes because we were having some issues with prettier that are now probably fixed.

2. Maybe we could call it just File instead of FileInput, what do you think?

3. I'm curious about defaultValue prop, what should we pass to it at all?

**Comment by italoiz** [comment]
@diego3g Do not you think switching from `<FileInput />` to `<File />` can get confusing in large forms? I think it's a good change, but I wonder if it's a great form.

About the "defaultValue". It may be interesting, for example, if there is an image previously sent, theoretically the default value would be a URL, so this value being sent to a backend would not be treated as a change, just in cases of a `base64` string.

**Comment by pellizzetti** [comment]
Since it's a `input` that handles `file(s)` I'm in favor of calling this component `FileInput`. :p

**Comment by jpdemagalhaes** [comment]
At first I was onboard with @diego3g to call it `File` instead of `FileInput`, but after reading @italoiz and @pellizzetti's answer I agree that we should keep it `FileInput`.

**Comment by diego3g** [comment]
@italoiz Let's keep with FileInput and i think we're ready to merge, i'll only ask one last code review from @jpdemagalhaes.

**Pull request merged**
