### PR TITLE
test: Small improvements on tests

### PR DESCRIPTION
**Pull request by JeffersonFilho**
**Changes proposed**

This contains some small improvements on the tests where the goal of it is to eliminate repetitive code across the tests and making tests easier to test.

### CODE REVIEW

**Comment by diego3g** [comment]
Hello @JeffersonFilho, can you fix your commit message according to our contribution guidelines? Thanks for the contribution btw.

**Comment by JeffersonFilho** [comment]
My bad @diego3g , hopefully is okay now

**Comment by diego3g** [comment]
@JeffersonFilho Hi, no problem. You left the old commit without changing it so the problem remains. You need to edit the old message "Add a setupTest file to hold all the imports necessary for the tests and a custom render" according to commit guidelines, it's too big and there is no subject prefixed like: `chore: Add setupTest file`

**Comment by JeffersonFilho** [comment]
I will close this PR since is becoming a mess with my attempts to merge the commits, I will fork this project again and apply the changes and commit following the contribution guidelines.

**Pull request closed without merging**
