### PR TITLE
Feature/multiple refs on register field

### LINKED ISSUE #20: [RFC] Checkbox implementation
Im thinking on the implementation of the checkbox functionality, and ended in this idea:
* work with an array of options, like select field
* options array will contain id and label (each option)
* getValue will return an array of checked ids

Well, let me know what you think about

### PR DESCRIPTION
**Pull request by rfbezerra**
**Changes proposed**
* Implement multiple refs to a registerField method
* Add a Choice field that has support to multiple options (checkboxes)

Tries to resolve #20 

**Additional context**
For now, every registered field has a ref property. This property, refers a input field.
With chackboxes, we need to have multiple fields to represent options.
For that reason we need multiple refs too.

### CODE REVIEW

**Comment by rfbezerra** [comment]
Hum, good points, lets talk....

1. its ok to separate in two components, maybe a _Checkbox_ (for a single option) and _Choice_ (to multiple options). So, in Choice component, if **multiple** property is supplied, we use checkboxes, if not, radios

2. I'll join up the two functions, no problem

3. I disabled that option because eslint complains about use hooks inside loops. Ill check

4. During my tests, I see multiple calls of registerField for the same field, resulting in a duplication of fields. If we have a large quantity of fields, maybe this became a problem

5. I didn't upgrade directly. I did a rebase to sync with master version, maybe that rebase update the package version.

I'll work in the points we have agreed.

**Comment by diego3g** [comment]
@rfbezerra Maybe a workaround for using ref inside loops: https://stackoverflow.com/a/56063129/1725849.

The multiple calls of registerField are being caused because your `useEffect` is not watching `refs` as the other form elements do.

**Comment by rfbezerra** [comment]
I did a new component to address single checkboxes, in #105 
In this PR, i will maintain only a component for multiple options

**Comment by rfbezerra** [comment]
Added two new components on #110

**Pull request closed without merging**
