### PR TITLE
test: Small improvements on tests

### PR DESCRIPTION
**Pull request by JeffersonFilho**
**Changes proposed**

This contains some small improvements on the tests where the goal of it is to eliminate repetitive code across the tests and making tests easier to test.

### CODE REVIEW

**Comment by diego3g** [comment]
What do you think about renaming RenderTest to `renderForm`?

**Comment by JeffersonFilho** [comment]
@diego3g We could go with `renderTest` or `renderTestForm`? I'm just bit worried it might get confused that it's a function which can be used in other places outside the tests files and I believe is always good to name files with keywords to what they do because makes easier to find afterwards.

What you think?

**Comment by diego3g** [comment]
@JeffersonFilho `renderTestForm` would be great! Also, i'm waiting to merge #110 before merging your PR since it's a PR that we've been working for more than one month. 

After that, that probably will happen this week, could you update your codebase to resolve conflicts with the new tests added on that PR? It would be great. 

Maybe you can anticipate yourself coding above that code and when we accept the PR you already have the code ready since we are only updating docs now.

**Comment by JeffersonFilho** [comment]
Yeah no problem, I will add the other tests into this PR later on today.

**Comment by diego3g** [comment]
Hi @JeffersonFilho, i merged #110 into master, can you update yours tests to include it?

**Comment by JeffersonFilho** [comment]
Should be okay now @diego3g

**Comment by JeffersonFilho** [comment]
Should be okay now @diego3g

**Pull request merged**
